### ISSUE TITLE
Add url to online view

### ISSUE THREAD

**Issue by zuphilip** [fbennett/legal-resource-registry#4]
Can you add the url to http://fbennett.github.io/legal-resource-registry/ in the repo description? (I had to google around before finding it...)

![add-url](https://cloud.githubusercontent.com/assets/5199995/26519534/0b7440e2-42c3-11e7-9230-7cf675960e3f.png)

**Comment by fbennett** [comment]
Done!

**Comment by zuphilip** [comment]
Thank you! 🙇
